# 此处token已经废弃，但是为了测试Telegram的hmac功能，需要保留一个真实token
bot-token: 554277510:AAEKxRdcRfhEjtSIfxpaYtL19XFgdDcY23U

god: 123456789


content-moderator:
  endpoint: "https://example-ocr.cognitiveservices.azure.com"
  api-key: "1234567890abcdef"
ocr:
  endpoint: "https://example-ocr.cognitiveservices.azure.com"
  api-key: '1234567890abcdef'
  api-ver: "2023-10-01"
  language: ""
  features: "Read"


qr-scan-url: http://localhost:4023/scanqr
tg-api-url: http://localhost:8081
drop-pending-updates: false
gemini-key: ABCDEFGHIJKLMNOPQRST
gemini-explicit-cache: true
deepseek-key: ""
deepseek-base-url: https://api.deepseek.com


log-level: -1
database-path: ":memory:"
ai-media-path: "ai-media"
my-chats: [-1001471592463]
