// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_bilibili.sql

package q

import (
	"context"
)

const createBiliInlineData = `-- name: CreateBiliInlineData :one
INSERT INTO bili_inline_results(created_at)
VALUES (?)
RETURNING uid
`

func (q *Queries) CreateBiliInlineData(ctx context.Context, createdAt UnixTime) (int64, error) {
	row := q.queryRow(ctx, q.createBiliInlineDataStmt, createBiliInlineData, createdAt)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const deleteExpiredBiliInlineData = `-- name: DeleteExpiredBiliInlineData :execrows
DELETE FROM bili_inline_results
WHERE created_at < ?
`

func (q *Queries) DeleteExpiredBiliInlineData(ctx context.Context, createdAt UnixTime) (int64, error) {
	result, err := q.exec(ctx, q.deleteExpiredBiliInlineDataStmt, deleteExpiredBiliInlineData, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBiliInlineData = `-- name: GetBiliInlineData :one

SELECT text, chat_id, msg_id
FROM bili_inline_results
WHERE uid = ?
  AND created_at >= ?
`

type GetBiliInlineDataRow struct {
	Text   string `json:"text"`
	ChatID int64  `json:"chat_id"`
	MsgID  int64  `json:"msg_id"`
}

// encoding: utf-8
func (q *Queries) GetBiliInlineData(ctx context.Context, uid int64, createdAt UnixTime) (GetBiliInlineDataRow, error) {
	row := q.queryRow(ctx, q.getBiliInlineDataStmt, getBiliInlineData, uid, createdAt)
	var i GetBiliInlineDataRow
	err := row.Scan(&i.Text, &i.ChatID, &i.MsgID)
	return i, err
}

const updateBiliInlineMsgId = `-- name: UpdateBiliInlineMsgId :exec
UPDATE bili_inline_results
SET text    = ?,
    chat_id = ?,
    msg_id  = ?
WHERE uid = ?
`

func (q *Queries) UpdateBiliInlineMsgId(ctx context.Context, text string, chatID int64, msgID int64, uid int64) error {
	_, err := q.exec(ctx, q.updateBiliInlineMsgIdStmt, updateBiliInlineMsgId,
		text,
		chatID,
		msgID,
		uid,
	)
	return err
}
