// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_user.sql

package q

import (
	"context"
	"database/sql"
)

const getPrprCache = `-- name: GetPrprCache :one
SELECT prpr_file_id
FROM prpr_caches
WHERE profile_photo_uid = ?
`

func (q *Queries) GetPrprCache(ctx context.Context, profilePhotoUid string) (string, error) {
	row := q.queryRow(ctx, q.getPrprCacheStmt, getPrprCache, profilePhotoUid)
	var prpr_file_id string
	err := row.Scan(&prpr_file_id)
	return prpr_file_id, err
}

const setPrprCache = `-- name: SetPrprCache :exec
INSERT INTO prpr_caches (profile_photo_uid, prpr_file_id)
VALUES (?, ?)
ON CONFLICT(profile_photo_uid) DO UPDATE SET prpr_file_id=excluded.prpr_file_id
`

func (q *Queries) SetPrprCache(ctx context.Context, profilePhotoUid string, prprFileID string) error {
	_, err := q.exec(ctx, q.setPrprCacheStmt, setPrprCache, profilePhotoUid, prprFileID)
	return err
}

const createNewUser = `-- name: createNewUser :one
INSERT INTO users (updated_at, user_id, first_name, last_name, username)
VALUES (?, ?, ?, ?, ?)
RETURNING user_id, updated_at, first_name, last_name, username
`

type createNewUserParams struct {
	UpdatedAt UnixTime       `json:"updated_at"`
	UserID    int64          `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Username  sql.NullString `json:"username"`
}

func (q *Queries) createNewUser(ctx context.Context, arg createNewUserParams) (User, error) {
	row := q.queryRow(ctx, q.createNewUserStmt, createNewUser,
		arg.UpdatedAt,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Username,
	)
	return i, err
}

const getUserById = `-- name: getUserById :one

SELECT user_id, updated_at, first_name, last_name, username
FROM users
WHERE user_id = ?
`

// encoding: utf-8
func (q *Queries) getUserById(ctx context.Context, userID int64) (User, error) {
	row := q.queryRow(ctx, q.getUserByIdStmt, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Username,
	)
	return i, err
}

const updateUserBase = `-- name: updateUserBase :one
UPDATE users
SET updated_at=?2,
    first_name=?3,
    last_name =?4,
    username  = ?5
WHERE user_id = ?1
RETURNING user_id, updated_at, first_name, last_name, username
`

type updateUserBaseParams struct {
	UserID    int64          `json:"user_id"`
	UpdatedAt UnixTime       `json:"updated_at"`
	FirstName string         `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Username  sql.NullString `json:"username"`
}

func (q *Queries) updateUserBase(ctx context.Context, arg updateUserBaseParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserBaseStmt, updateUserBase,
		arg.UserID,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Username,
	)
	return i, err
}
