// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package aiq

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addAIMessageMediaStmt, err = db.PrepareContext(ctx, addAIMessageMedia); err != nil {
		return nil, fmt.Errorf("error preparing query AddAIMessageMedia: %w", err)
	}
	if q.addAISessionMessageStmt, err = db.PrepareContext(ctx, addAISessionMessage); err != nil {
		return nil, fmt.Errorf("error preparing query AddAISessionMessage: %w", err)
	}
	if q.createAIRunStmt, err = db.PrepareContext(ctx, createAIRun); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAIRun: %w", err)
	}
	if q.createAISessionStmt, err = db.PrepareContext(ctx, createAISession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAISession: %w", err)
	}
	if q.deleteAISessionProviderStateStmt, err = db.PrepareContext(ctx, deleteAISessionProviderState); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAISessionProviderState: %w", err)
	}
	if q.deleteAISystemPromptStmt, err = db.PrepareContext(ctx, deleteAISystemPrompt); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAISystemPrompt: %w", err)
	}
	if q.getAIChatSettingsStmt, err = db.PrepareContext(ctx, getAIChatSettings); err != nil {
		return nil, fmt.Errorf("error preparing query GetAIChatSettings: %w", err)
	}
	if q.getAIMessageStmt, err = db.PrepareContext(ctx, getAIMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetAIMessage: %w", err)
	}
	if q.getAIRunByRequestStmt, err = db.PrepareContext(ctx, getAIRunByRequest); err != nil {
		return nil, fmt.Errorf("error preparing query GetAIRunByRequest: %w", err)
	}
	if q.getAIRunByResponseStmt, err = db.PrepareContext(ctx, getAIRunByResponse); err != nil {
		return nil, fmt.Errorf("error preparing query GetAIRunByResponse: %w", err)
	}
	if q.getAISessionStmt, err = db.PrepareContext(ctx, getAISession); err != nil {
		return nil, fmt.Errorf("error preparing query GetAISession: %w", err)
	}
	if q.getAISessionProviderStateStmt, err = db.PrepareContext(ctx, getAISessionProviderState); err != nil {
		return nil, fmt.Errorf("error preparing query GetAISessionProviderState: %w", err)
	}
	if q.getAISystemPromptStmt, err = db.PrepareContext(ctx, getAISystemPrompt); err != nil {
		return nil, fmt.Errorf("error preparing query GetAISystemPrompt: %w", err)
	}
	if q.getMediaObjectStmt, err = db.PrepareContext(ctx, getMediaObject); err != nil {
		return nil, fmt.Errorf("error preparing query GetMediaObject: %w", err)
	}
	if q.incrementAISessionUsageStmt, err = db.PrepareContext(ctx, incrementAISessionUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementAISessionUsage: %w", err)
	}
	if q.insertAIMessageStmt, err = db.PrepareContext(ctx, insertAIMessage); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAIMessage: %w", err)
	}
	if q.insertMediaObjectStmt, err = db.PrepareContext(ctx, insertMediaObject); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMediaObject: %w", err)
	}
	if q.listAIMessageMediaStmt, err = db.PrepareContext(ctx, listAIMessageMedia); err != nil {
		return nil, fmt.Errorf("error preparing query ListAIMessageMedia: %w", err)
	}
	if q.listAISessionMessagesStmt, err = db.PrepareContext(ctx, listAISessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAISessionMessages: %w", err)
	}
	if q.listReferencedMediaHashesStmt, err = db.PrepareContext(ctx, listReferencedMediaHashes); err != nil {
		return nil, fmt.Errorf("error preparing query ListReferencedMediaHashes: %w", err)
	}
	if q.markAIRunDeliveredStmt, err = db.PrepareContext(ctx, markAIRunDelivered); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAIRunDelivered: %w", err)
	}
	if q.markAIRunFailedStmt, err = db.PrepareContext(ctx, markAIRunFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAIRunFailed: %w", err)
	}
	if q.markAIRunGeneratedStmt, err = db.PrepareContext(ctx, markAIRunGenerated); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAIRunGenerated: %w", err)
	}
	if q.setAISessionModelStmt, err = db.PrepareContext(ctx, setAISessionModel); err != nil {
		return nil, fmt.Errorf("error preparing query SetAISessionModel: %w", err)
	}
	if q.setAISessionStatusStmt, err = db.PrepareContext(ctx, setAISessionStatus); err != nil {
		return nil, fmt.Errorf("error preparing query SetAISessionStatus: %w", err)
	}
	if q.toggleAIChatSettingsUsageStmt, err = db.PrepareContext(ctx, toggleAIChatSettingsUsage); err != nil {
		return nil, fmt.Errorf("error preparing query ToggleAIChatSettingsUsage: %w", err)
	}
	if q.upsertAIChatSettingsStmt, err = db.PrepareContext(ctx, upsertAIChatSettings); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAIChatSettings: %w", err)
	}
	if q.upsertAISessionProviderStateStmt, err = db.PrepareContext(ctx, upsertAISessionProviderState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAISessionProviderState: %w", err)
	}
	if q.upsertAISystemPromptStmt, err = db.PrepareContext(ctx, upsertAISystemPrompt); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAISystemPrompt: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addAIMessageMediaStmt != nil {
		if cerr := q.addAIMessageMediaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAIMessageMediaStmt: %w", cerr)
		}
	}
	if q.addAISessionMessageStmt != nil {
		if cerr := q.addAISessionMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAISessionMessageStmt: %w", cerr)
		}
	}
	if q.createAIRunStmt != nil {
		if cerr := q.createAIRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAIRunStmt: %w", cerr)
		}
	}
	if q.createAISessionStmt != nil {
		if cerr := q.createAISessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAISessionStmt: %w", cerr)
		}
	}
	if q.deleteAISessionProviderStateStmt != nil {
		if cerr := q.deleteAISessionProviderStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAISessionProviderStateStmt: %w", cerr)
		}
	}
	if q.deleteAISystemPromptStmt != nil {
		if cerr := q.deleteAISystemPromptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAISystemPromptStmt: %w", cerr)
		}
	}
	if q.getAIChatSettingsStmt != nil {
		if cerr := q.getAIChatSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAIChatSettingsStmt: %w", cerr)
		}
	}
	if q.getAIMessageStmt != nil {
		if cerr := q.getAIMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAIMessageStmt: %w", cerr)
		}
	}
	if q.getAIRunByRequestStmt != nil {
		if cerr := q.getAIRunByRequestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAIRunByRequestStmt: %w", cerr)
		}
	}
	if q.getAIRunByResponseStmt != nil {
		if cerr := q.getAIRunByResponseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAIRunByResponseStmt: %w", cerr)
		}
	}
	if q.getAISessionStmt != nil {
		if cerr := q.getAISessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAISessionStmt: %w", cerr)
		}
	}
	if q.getAISessionProviderStateStmt != nil {
		if cerr := q.getAISessionProviderStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAISessionProviderStateStmt: %w", cerr)
		}
	}
	if q.getAISystemPromptStmt != nil {
		if cerr := q.getAISystemPromptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAISystemPromptStmt: %w", cerr)
		}
	}
	if q.getMediaObjectStmt != nil {
		if cerr := q.getMediaObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMediaObjectStmt: %w", cerr)
		}
	}
	if q.incrementAISessionUsageStmt != nil {
		if cerr := q.incrementAISessionUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementAISessionUsageStmt: %w", cerr)
		}
	}
	if q.insertAIMessageStmt != nil {
		if cerr := q.insertAIMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAIMessageStmt: %w", cerr)
		}
	}
	if q.insertMediaObjectStmt != nil {
		if cerr := q.insertMediaObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMediaObjectStmt: %w", cerr)
		}
	}
	if q.listAIMessageMediaStmt != nil {
		if cerr := q.listAIMessageMediaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAIMessageMediaStmt: %w", cerr)
		}
	}
	if q.listAISessionMessagesStmt != nil {
		if cerr := q.listAISessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAISessionMessagesStmt: %w", cerr)
		}
	}
	if q.listReferencedMediaHashesStmt != nil {
		if cerr := q.listReferencedMediaHashesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReferencedMediaHashesStmt: %w", cerr)
		}
	}
	if q.markAIRunDeliveredStmt != nil {
		if cerr := q.markAIRunDeliveredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAIRunDeliveredStmt: %w", cerr)
		}
	}
	if q.markAIRunFailedStmt != nil {
		if cerr := q.markAIRunFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAIRunFailedStmt: %w", cerr)
		}
	}
	if q.markAIRunGeneratedStmt != nil {
		if cerr := q.markAIRunGeneratedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAIRunGeneratedStmt: %w", cerr)
		}
	}
	if q.setAISessionModelStmt != nil {
		if cerr := q.setAISessionModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAISessionModelStmt: %w", cerr)
		}
	}
	if q.setAISessionStatusStmt != nil {
		if cerr := q.setAISessionStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAISessionStatusStmt: %w", cerr)
		}
	}
	if q.toggleAIChatSettingsUsageStmt != nil {
		if cerr := q.toggleAIChatSettingsUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing toggleAIChatSettingsUsageStmt: %w", cerr)
		}
	}
	if q.upsertAIChatSettingsStmt != nil {
		if cerr := q.upsertAIChatSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAIChatSettingsStmt: %w", cerr)
		}
	}
	if q.upsertAISessionProviderStateStmt != nil {
		if cerr := q.upsertAISessionProviderStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAISessionProviderStateStmt: %w", cerr)
		}
	}
	if q.upsertAISystemPromptStmt != nil {
		if cerr := q.upsertAISystemPromptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAISystemPromptStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	addAIMessageMediaStmt            *sql.Stmt
	addAISessionMessageStmt          *sql.Stmt
	createAIRunStmt                  *sql.Stmt
	createAISessionStmt              *sql.Stmt
	deleteAISessionProviderStateStmt *sql.Stmt
	deleteAISystemPromptStmt         *sql.Stmt
	getAIChatSettingsStmt            *sql.Stmt
	getAIMessageStmt                 *sql.Stmt
	getAIRunByRequestStmt            *sql.Stmt
	getAIRunByResponseStmt           *sql.Stmt
	getAISessionStmt                 *sql.Stmt
	getAISessionProviderStateStmt    *sql.Stmt
	getAISystemPromptStmt            *sql.Stmt
	getMediaObjectStmt               *sql.Stmt
	incrementAISessionUsageStmt      *sql.Stmt
	insertAIMessageStmt              *sql.Stmt
	insertMediaObjectStmt            *sql.Stmt
	listAIMessageMediaStmt           *sql.Stmt
	listAISessionMessagesStmt        *sql.Stmt
	listReferencedMediaHashesStmt    *sql.Stmt
	markAIRunDeliveredStmt           *sql.Stmt
	markAIRunFailedStmt              *sql.Stmt
	markAIRunGeneratedStmt           *sql.Stmt
	setAISessionModelStmt            *sql.Stmt
	setAISessionStatusStmt           *sql.Stmt
	toggleAIChatSettingsUsageStmt    *sql.Stmt
	upsertAIChatSettingsStmt         *sql.Stmt
	upsertAISessionProviderStateStmt *sql.Stmt
	upsertAISystemPromptStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		addAIMessageMediaStmt:            q.addAIMessageMediaStmt,
		addAISessionMessageStmt:          q.addAISessionMessageStmt,
		createAIRunStmt:                  q.createAIRunStmt,
		createAISessionStmt:              q.createAISessionStmt,
		deleteAISessionProviderStateStmt: q.deleteAISessionProviderStateStmt,
		deleteAISystemPromptStmt:         q.deleteAISystemPromptStmt,
		getAIChatSettingsStmt:            q.getAIChatSettingsStmt,
		getAIMessageStmt:                 q.getAIMessageStmt,
		getAIRunByRequestStmt:            q.getAIRunByRequestStmt,
		getAIRunByResponseStmt:           q.getAIRunByResponseStmt,
		getAISessionStmt:                 q.getAISessionStmt,
		getAISessionProviderStateStmt:    q.getAISessionProviderStateStmt,
		getAISystemPromptStmt:            q.getAISystemPromptStmt,
		getMediaObjectStmt:               q.getMediaObjectStmt,
		incrementAISessionUsageStmt:      q.incrementAISessionUsageStmt,
		insertAIMessageStmt:              q.insertAIMessageStmt,
		insertMediaObjectStmt:            q.insertMediaObjectStmt,
		listAIMessageMediaStmt:           q.listAIMessageMediaStmt,
		listAISessionMessagesStmt:        q.listAISessionMessagesStmt,
		listReferencedMediaHashesStmt:    q.listReferencedMediaHashesStmt,
		markAIRunDeliveredStmt:           q.markAIRunDeliveredStmt,
		markAIRunFailedStmt:              q.markAIRunFailedStmt,
		markAIRunGeneratedStmt:           q.markAIRunGeneratedStmt,
		setAISessionModelStmt:            q.setAISessionModelStmt,
		setAISessionStatusStmt:           q.setAISessionStatusStmt,
		toggleAIChatSettingsUsageStmt:    q.toggleAIChatSettingsUsageStmt,
		upsertAIChatSettingsStmt:         q.upsertAIChatSettingsStmt,
		upsertAISessionProviderStateStmt: q.upsertAISessionProviderStateStmt,
		upsertAISystemPromptStmt:         q.upsertAISystemPromptStmt,
	}
}
