// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package aiq

import (
	"database/sql"
)

type AiChatSetting struct {
	ChatID          int64  `json:"chat_id"`
	DefaultProvider string `json:"default_provider"`
	DefaultModel    string `json:"default_model"`
	ShowUsage       int64  `json:"show_usage"`
	UpdatedAt       int64  `json:"updated_at"`
}

type AiMessage struct {
	ChatID         int64          `json:"chat_id"`
	MsgID          int64          `json:"msg_id"`
	SentAt         int64          `json:"sent_at"`
	UserID         int64          `json:"user_id"`
	Username       string         `json:"username"`
	AtableUsername sql.NullString `json:"atable_username"`
	MsgType        string         `json:"msg_type"`
	Text           sql.NullString `json:"text"`
	ReplyToMsgID   sql.NullInt64  `json:"reply_to_msg_id"`
}

type AiMessageMedium struct {
	ChatID      int64  `json:"chat_id"`
	MsgID       int64  `json:"msg_id"`
	Ordinal     int64  `json:"ordinal"`
	MediaSha256 string `json:"media_sha256"`
	MediaKind   string `json:"media_kind"`
}

type AiRun struct {
	ID                     int64          `json:"id"`
	SessionID              int64          `json:"session_id"`
	RequestChatID          int64          `json:"request_chat_id"`
	RequestMsgID           int64          `json:"request_msg_id"`
	Status                 string         `json:"status"`
	Provider               string         `json:"provider"`
	Model                  string         `json:"model"`
	RequestedAt            int64          `json:"requested_at"`
	CompletedAt            sql.NullInt64  `json:"completed_at"`
	InputTokens            sql.NullInt64  `json:"input_tokens"`
	OutputTokens           sql.NullInt64  `json:"output_tokens"`
	CachedInputTokens      sql.NullInt64  `json:"cached_input_tokens"`
	InputMessageCount      sql.NullInt64  `json:"input_message_count"`
	InputFirstMsgID        sql.NullInt64  `json:"input_first_msg_id"`
	InputLastMsgID         sql.NullInt64  `json:"input_last_msg_id"`
	ResponseText           sql.NullString `json:"response_text"`
	ThoughtSignature       sql.NullString `json:"thought_signature"`
	AssistantPayload       []byte         `json:"assistant_payload"`
	AssistantPayloadFormat sql.NullString `json:"assistant_payload_format"`
	CacheExpireAt          sql.NullInt64  `json:"cache_expire_at"`
	CandidateStateJson     sql.NullString `json:"candidate_state_json"`
	ResponseChatID         sql.NullInt64  `json:"response_chat_id"`
	ResponseMsgID          sql.NullInt64  `json:"response_msg_id"`
	ErrorCode              sql.NullString `json:"error_code"`
	ErrorMessage           sql.NullString `json:"error_message"`
}

type AiSession struct {
	ID                     int64         `json:"id"`
	ChatID                 int64         `json:"chat_id"`
	TopicID                sql.NullInt64 `json:"topic_id"`
	ChatName               string        `json:"chat_name"`
	ChatType               string        `json:"chat_type"`
	Status                 string        `json:"status"`
	Provider               string        `json:"provider"`
	Model                  string        `json:"model"`
	CreatedAt              int64         `json:"created_at"`
	UpdatedAt              int64         `json:"updated_at"`
	TotalInputTokens       int64         `json:"total_input_tokens"`
	TotalOutputTokens      int64         `json:"total_output_tokens"`
	TotalCachedInputTokens int64         `json:"total_cached_input_tokens"`
	HistoryRebuildLossy    int64         `json:"history_rebuild_lossy"`
}

type AiSessionMessage struct {
	SessionID   int64          `json:"session_id"`
	Position    int64          `json:"position"`
	ChatID      int64          `json:"chat_id"`
	MsgID       int64          `json:"msg_id"`
	Role        string         `json:"role"`
	QuotePart   sql.NullString `json:"quote_part"`
	ContextOnly int64          `json:"context_only"`
}

type AiSessionProviderState struct {
	SessionID    int64  `json:"session_id"`
	Provider     string `json:"provider"`
	StateVersion int64  `json:"state_version"`
	StateJson    string `json:"state_json"`
	UpdatedAt    int64  `json:"updated_at"`
}

type AiSystemPrompt struct {
	ChatID    int64  `json:"chat_id"`
	TopicID   int64  `json:"topic_id"`
	Prompt    string `json:"prompt"`
	UpdatedAt int64  `json:"updated_at"`
}

type MediaObject struct {
	Sha256       string `json:"sha256"`
	RelativePath string `json:"relative_path"`
	ByteSize     int64  `json:"byte_size"`
	MimeType     string `json:"mime_type"`
	CreatedAt    int64  `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	Name      string `json:"name"`
	Checksum  string `json:"checksum"`
	AppliedAt int64  `json:"applied_at"`
}
