// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_ai_v2.sql

package aiq

import (
	"context"
	"database/sql"
)

const addAIMessageMedia = `-- name: AddAIMessageMedia :exec
INSERT INTO ai_message_media(chat_id, msg_id, ordinal, media_sha256, media_kind)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(chat_id, msg_id, ordinal) DO NOTHING
`

type AddAIMessageMediaParams struct {
	ChatID      int64  `json:"chat_id"`
	MsgID       int64  `json:"msg_id"`
	Ordinal     int64  `json:"ordinal"`
	MediaSha256 string `json:"media_sha256"`
	MediaKind   string `json:"media_kind"`
}

func (q *Queries) AddAIMessageMedia(ctx context.Context, arg AddAIMessageMediaParams) error {
	_, err := q.exec(ctx, q.addAIMessageMediaStmt, addAIMessageMedia,
		arg.ChatID,
		arg.MsgID,
		arg.Ordinal,
		arg.MediaSha256,
		arg.MediaKind,
	)
	return err
}

const addAISessionMessage = `-- name: AddAISessionMessage :exec
INSERT INTO ai_session_messages(session_id, position, chat_id, msg_id, role, quote_part, context_only)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7)
ON CONFLICT(session_id, chat_id, msg_id) DO NOTHING
`

type AddAISessionMessageParams struct {
	SessionID   int64          `json:"session_id"`
	Position    int64          `json:"position"`
	ChatID      int64          `json:"chat_id"`
	MsgID       int64          `json:"msg_id"`
	Role        string         `json:"role"`
	QuotePart   sql.NullString `json:"quote_part"`
	ContextOnly int64          `json:"context_only"`
}

func (q *Queries) AddAISessionMessage(ctx context.Context, arg AddAISessionMessageParams) error {
	_, err := q.exec(ctx, q.addAISessionMessageStmt, addAISessionMessage,
		arg.SessionID,
		arg.Position,
		arg.ChatID,
		arg.MsgID,
		arg.Role,
		arg.QuotePart,
		arg.ContextOnly,
	)
	return err
}

const clearAISessionHistoryRebuildLossy = `-- name: ClearAISessionHistoryRebuildLossy :exec
UPDATE ai_sessions
SET history_rebuild_lossy=0, updated_at=?1
WHERE id=?2
`

func (q *Queries) ClearAISessionHistoryRebuildLossy(ctx context.Context, updatedAt int64, sessionID int64) error {
	_, err := q.exec(ctx, q.clearAISessionHistoryRebuildLossyStmt, clearAISessionHistoryRebuildLossy, updatedAt, sessionID)
	return err
}

const createAIRun = `-- name: CreateAIRun :one
INSERT INTO ai_runs(session_id, request_chat_id, request_msg_id, status, provider, model, requested_at)
VALUES (?1, ?2, ?3,
        'pending', ?4, ?5, ?6)
ON CONFLICT(session_id, request_chat_id, request_msg_id) DO UPDATE SET id=id
RETURNING id, session_id, request_chat_id, request_msg_id, status, provider, model, requested_at, completed_at, input_tokens, output_tokens, cached_input_tokens, input_message_count, input_first_msg_id, input_last_msg_id, response_text, raw_payload, thought_signature, assistant_payload, assistant_payload_format, cache_expire_at, candidate_state_json, response_chat_id, response_msg_id, error_code, error_message
`

type CreateAIRunParams struct {
	SessionID     int64  `json:"session_id"`
	RequestChatID int64  `json:"request_chat_id"`
	RequestMsgID  int64  `json:"request_msg_id"`
	Provider      string `json:"provider"`
	Model         string `json:"model"`
	RequestedAt   int64  `json:"requested_at"`
}

func (q *Queries) CreateAIRun(ctx context.Context, arg CreateAIRunParams) (AiRun, error) {
	row := q.queryRow(ctx, q.createAIRunStmt, createAIRun,
		arg.SessionID,
		arg.RequestChatID,
		arg.RequestMsgID,
		arg.Provider,
		arg.Model,
		arg.RequestedAt,
	)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestChatID,
		&i.RequestMsgID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.InputMessageCount,
		&i.InputFirstMsgID,
		&i.InputLastMsgID,
		&i.ResponseText,
		&i.RawPayload,
		&i.ThoughtSignature,
		&i.AssistantPayload,
		&i.AssistantPayloadFormat,
		&i.CacheExpireAt,
		&i.CandidateStateJson,
		&i.ResponseChatID,
		&i.ResponseMsgID,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const createAISession = `-- name: CreateAISession :one
INSERT INTO ai_sessions(chat_id, topic_id, chat_name, chat_type, provider, model, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7, ?8)
RETURNING id, chat_id, topic_id, chat_name, chat_type, status, provider, model, created_at, updated_at, total_input_tokens, total_output_tokens, total_cached_input_tokens, history_rebuild_lossy
`

type CreateAISessionParams struct {
	ChatID    int64         `json:"chat_id"`
	TopicID   sql.NullInt64 `json:"topic_id"`
	ChatName  string        `json:"chat_name"`
	ChatType  string        `json:"chat_type"`
	Provider  string        `json:"provider"`
	Model     string        `json:"model"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}

func (q *Queries) CreateAISession(ctx context.Context, arg CreateAISessionParams) (AiSession, error) {
	row := q.queryRow(ctx, q.createAISessionStmt, createAISession,
		arg.ChatID,
		arg.TopicID,
		arg.ChatName,
		arg.ChatType,
		arg.Provider,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AiSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.ChatName,
		&i.ChatType,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCachedInputTokens,
		&i.HistoryRebuildLossy,
	)
	return i, err
}

const deleteAISessionProviderState = `-- name: DeleteAISessionProviderState :exec
DELETE FROM ai_session_provider_state WHERE session_id=?
`

func (q *Queries) DeleteAISessionProviderState(ctx context.Context, sessionID int64) error {
	_, err := q.exec(ctx, q.deleteAISessionProviderStateStmt, deleteAISessionProviderState, sessionID)
	return err
}

const deleteAISystemPrompt = `-- name: DeleteAISystemPrompt :exec
DELETE FROM ai_system_prompts WHERE chat_id=? AND topic_id=?
`

func (q *Queries) DeleteAISystemPrompt(ctx context.Context, chatID int64, topicID int64) error {
	_, err := q.exec(ctx, q.deleteAISystemPromptStmt, deleteAISystemPrompt, chatID, topicID)
	return err
}

const getAIChatSettings = `-- name: GetAIChatSettings :one
SELECT chat_id, default_provider, default_model, show_usage, updated_at FROM ai_chat_settings WHERE chat_id = ?
`

func (q *Queries) GetAIChatSettings(ctx context.Context, chatID int64) (AiChatSetting, error) {
	row := q.queryRow(ctx, q.getAIChatSettingsStmt, getAIChatSettings, chatID)
	var i AiChatSetting
	err := row.Scan(
		&i.ChatID,
		&i.DefaultProvider,
		&i.DefaultModel,
		&i.ShowUsage,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIMessage = `-- name: GetAIMessage :one
SELECT chat_id, msg_id, sent_at, user_id, username, atable_username, msg_type, text, reply_to_msg_id FROM ai_messages WHERE chat_id=? AND msg_id=?
`

func (q *Queries) GetAIMessage(ctx context.Context, chatID int64, msgID int64) (AiMessage, error) {
	row := q.queryRow(ctx, q.getAIMessageStmt, getAIMessage, chatID, msgID)
	var i AiMessage
	err := row.Scan(
		&i.ChatID,
		&i.MsgID,
		&i.SentAt,
		&i.UserID,
		&i.Username,
		&i.AtableUsername,
		&i.MsgType,
		&i.Text,
		&i.ReplyToMsgID,
	)
	return i, err
}

const getAIRun = `-- name: GetAIRun :one
SELECT id, session_id, request_chat_id, request_msg_id, status, provider, model, requested_at, completed_at, input_tokens, output_tokens, cached_input_tokens, input_message_count, input_first_msg_id, input_last_msg_id, response_text, raw_payload, thought_signature, assistant_payload, assistant_payload_format, cache_expire_at, candidate_state_json, response_chat_id, response_msg_id, error_code, error_message FROM ai_runs WHERE id=?
`

func (q *Queries) GetAIRun(ctx context.Context, id int64) (AiRun, error) {
	row := q.queryRow(ctx, q.getAIRunStmt, getAIRun, id)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestChatID,
		&i.RequestMsgID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.InputMessageCount,
		&i.InputFirstMsgID,
		&i.InputLastMsgID,
		&i.ResponseText,
		&i.RawPayload,
		&i.ThoughtSignature,
		&i.AssistantPayload,
		&i.AssistantPayloadFormat,
		&i.CacheExpireAt,
		&i.CandidateStateJson,
		&i.ResponseChatID,
		&i.ResponseMsgID,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getAIRunByRequest = `-- name: GetAIRunByRequest :one
SELECT id, session_id, request_chat_id, request_msg_id, status, provider, model, requested_at, completed_at, input_tokens, output_tokens, cached_input_tokens, input_message_count, input_first_msg_id, input_last_msg_id, response_text, raw_payload, thought_signature, assistant_payload, assistant_payload_format, cache_expire_at, candidate_state_json, response_chat_id, response_msg_id, error_code, error_message FROM ai_runs
WHERE session_id=? AND request_chat_id=? AND request_msg_id=?
`

func (q *Queries) GetAIRunByRequest(ctx context.Context, sessionID int64, requestChatID int64, requestMsgID int64) (AiRun, error) {
	row := q.queryRow(ctx, q.getAIRunByRequestStmt, getAIRunByRequest, sessionID, requestChatID, requestMsgID)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestChatID,
		&i.RequestMsgID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.InputMessageCount,
		&i.InputFirstMsgID,
		&i.InputLastMsgID,
		&i.ResponseText,
		&i.RawPayload,
		&i.ThoughtSignature,
		&i.AssistantPayload,
		&i.AssistantPayloadFormat,
		&i.CacheExpireAt,
		&i.CandidateStateJson,
		&i.ResponseChatID,
		&i.ResponseMsgID,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getAIRunByResponse = `-- name: GetAIRunByResponse :one
SELECT id, session_id, request_chat_id, request_msg_id, status, provider, model, requested_at, completed_at, input_tokens, output_tokens, cached_input_tokens, input_message_count, input_first_msg_id, input_last_msg_id, response_text, raw_payload, thought_signature, assistant_payload, assistant_payload_format, cache_expire_at, candidate_state_json, response_chat_id, response_msg_id, error_code, error_message FROM ai_runs WHERE response_chat_id=? AND response_msg_id=?
`

func (q *Queries) GetAIRunByResponse(ctx context.Context, responseChatID sql.NullInt64, responseMsgID sql.NullInt64) (AiRun, error) {
	row := q.queryRow(ctx, q.getAIRunByResponseStmt, getAIRunByResponse, responseChatID, responseMsgID)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestChatID,
		&i.RequestMsgID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.InputMessageCount,
		&i.InputFirstMsgID,
		&i.InputLastMsgID,
		&i.ResponseText,
		&i.RawPayload,
		&i.ThoughtSignature,
		&i.AssistantPayload,
		&i.AssistantPayloadFormat,
		&i.CacheExpireAt,
		&i.CandidateStateJson,
		&i.ResponseChatID,
		&i.ResponseMsgID,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getAISession = `-- name: GetAISession :one
SELECT id, chat_id, topic_id, chat_name, chat_type, status, provider, model, created_at, updated_at, total_input_tokens, total_output_tokens, total_cached_input_tokens, history_rebuild_lossy FROM ai_sessions WHERE id = ?
`

func (q *Queries) GetAISession(ctx context.Context, id int64) (AiSession, error) {
	row := q.queryRow(ctx, q.getAISessionStmt, getAISession, id)
	var i AiSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.ChatName,
		&i.ChatType,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCachedInputTokens,
		&i.HistoryRebuildLossy,
	)
	return i, err
}

const getAISessionIDByMessage = `-- name: GetAISessionIDByMessage :one
SELECT sm.session_id
FROM ai_session_messages AS sm
JOIN ai_sessions AS s ON s.id = sm.session_id
WHERE sm.chat_id = ?1 AND sm.msg_id = ?2
  AND sm.context_only=0
ORDER BY s.updated_at DESC, sm.session_id DESC
LIMIT 1
`

func (q *Queries) GetAISessionIDByMessage(ctx context.Context, chatID int64, msgID int64) (int64, error) {
	row := q.queryRow(ctx, q.getAISessionIDByMessageStmt, getAISessionIDByMessage, chatID, msgID)
	var session_id int64
	err := row.Scan(&session_id)
	return session_id, err
}

const getAISessionProviderState = `-- name: GetAISessionProviderState :one
SELECT session_id, provider, state_version, state_json, updated_at FROM ai_session_provider_state WHERE session_id=?
`

func (q *Queries) GetAISessionProviderState(ctx context.Context, sessionID int64) (AiSessionProviderState, error) {
	row := q.queryRow(ctx, q.getAISessionProviderStateStmt, getAISessionProviderState, sessionID)
	var i AiSessionProviderState
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.StateVersion,
		&i.StateJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getAISystemPrompt = `-- name: GetAISystemPrompt :one
SELECT prompt FROM ai_system_prompts WHERE chat_id=? AND topic_id=?
`

func (q *Queries) GetAISystemPrompt(ctx context.Context, chatID int64, topicID int64) (string, error) {
	row := q.queryRow(ctx, q.getAISystemPromptStmt, getAISystemPrompt, chatID, topicID)
	var prompt string
	err := row.Scan(&prompt)
	return prompt, err
}

const getMediaObject = `-- name: GetMediaObject :one
SELECT sha256, relative_path, byte_size, mime_type, created_at FROM media_objects WHERE sha256=?
`

func (q *Queries) GetMediaObject(ctx context.Context, sha256 string) (MediaObject, error) {
	row := q.queryRow(ctx, q.getMediaObjectStmt, getMediaObject, sha256)
	var i MediaObject
	err := row.Scan(
		&i.Sha256,
		&i.RelativePath,
		&i.ByteSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getNextAISessionMessagePosition = `-- name: GetNextAISessionMessagePosition :one
SELECT CAST(COALESCE(MAX(position) + 1, 0) AS INTEGER)
FROM ai_session_messages
WHERE session_id = ?
`

func (q *Queries) GetNextAISessionMessagePosition(ctx context.Context, sessionID int64) (int64, error) {
	row := q.queryRow(ctx, q.getNextAISessionMessagePositionStmt, getNextAISessionMessagePosition, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementAISessionUsage = `-- name: IncrementAISessionUsage :exec
UPDATE ai_sessions
SET total_input_tokens=total_input_tokens + ?1,
    total_output_tokens=total_output_tokens + ?2,
    total_cached_input_tokens=total_cached_input_tokens + ?3,
    updated_at=?4
WHERE id=?5
`

type IncrementAISessionUsageParams struct {
	InputTokens       int64 `json:"input_tokens"`
	OutputTokens      int64 `json:"output_tokens"`
	CachedInputTokens int64 `json:"cached_input_tokens"`
	UpdatedAt         int64 `json:"updated_at"`
	SessionID         int64 `json:"session_id"`
}

func (q *Queries) IncrementAISessionUsage(ctx context.Context, arg IncrementAISessionUsageParams) error {
	_, err := q.exec(ctx, q.incrementAISessionUsageStmt, incrementAISessionUsage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedInputTokens,
		arg.UpdatedAt,
		arg.SessionID,
	)
	return err
}

const insertAIMessage = `-- name: InsertAIMessage :exec
INSERT INTO ai_messages(chat_id, msg_id, sent_at, user_id, username, atable_username,
                        msg_type, text, reply_to_msg_id)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7, ?8,
        ?9)
ON CONFLICT(chat_id, msg_id) DO NOTHING
`

type InsertAIMessageParams struct {
	ChatID         int64          `json:"chat_id"`
	MsgID          int64          `json:"msg_id"`
	SentAt         int64          `json:"sent_at"`
	UserID         int64          `json:"user_id"`
	Username       string         `json:"username"`
	AtableUsername sql.NullString `json:"atable_username"`
	MsgType        string         `json:"msg_type"`
	Text           sql.NullString `json:"text"`
	ReplyToMsgID   sql.NullInt64  `json:"reply_to_msg_id"`
}

func (q *Queries) InsertAIMessage(ctx context.Context, arg InsertAIMessageParams) error {
	_, err := q.exec(ctx, q.insertAIMessageStmt, insertAIMessage,
		arg.ChatID,
		arg.MsgID,
		arg.SentAt,
		arg.UserID,
		arg.Username,
		arg.AtableUsername,
		arg.MsgType,
		arg.Text,
		arg.ReplyToMsgID,
	)
	return err
}

const insertMediaObject = `-- name: InsertMediaObject :exec
INSERT INTO media_objects(sha256, relative_path, byte_size, mime_type, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(sha256) DO NOTHING
`

type InsertMediaObjectParams struct {
	Sha256       string `json:"sha256"`
	RelativePath string `json:"relative_path"`
	ByteSize     int64  `json:"byte_size"`
	MimeType     string `json:"mime_type"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) error {
	_, err := q.exec(ctx, q.insertMediaObjectStmt, insertMediaObject,
		arg.Sha256,
		arg.RelativePath,
		arg.ByteSize,
		arg.MimeType,
		arg.CreatedAt,
	)
	return err
}

const listAIMessageMedia = `-- name: ListAIMessageMedia :many
SELECT m.sha256, m.relative_path, m.byte_size, m.mime_type, m.created_at
FROM media_objects m
JOIN ai_message_media mm ON mm.media_sha256=m.sha256
WHERE mm.chat_id=? AND mm.msg_id=?
ORDER BY mm.ordinal
`

func (q *Queries) ListAIMessageMedia(ctx context.Context, chatID int64, msgID int64) ([]MediaObject, error) {
	rows, err := q.query(ctx, q.listAIMessageMediaStmt, listAIMessageMedia, chatID, msgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaObject
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.Sha256,
			&i.RelativePath,
			&i.ByteSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAISessionAssistantRuns = `-- name: ListAISessionAssistantRuns :many
SELECT id, session_id, request_chat_id, request_msg_id, status, provider, model, requested_at, completed_at, input_tokens, output_tokens, cached_input_tokens, input_message_count, input_first_msg_id, input_last_msg_id, response_text, raw_payload, thought_signature, assistant_payload, assistant_payload_format, cache_expire_at, candidate_state_json, response_chat_id, response_msg_id, error_code, error_message FROM ai_runs
WHERE session_id=? AND status='delivered'
  AND response_msg_id IS NOT NULL
  AND assistant_payload IS NOT NULL
  AND assistant_payload_format IS NOT NULL
ORDER BY requested_at, id
`

func (q *Queries) ListAISessionAssistantRuns(ctx context.Context, sessionID int64) ([]AiRun, error) {
	rows, err := q.query(ctx, q.listAISessionAssistantRunsStmt, listAISessionAssistantRuns, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiRun
	for rows.Next() {
		var i AiRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RequestChatID,
			&i.RequestMsgID,
			&i.Status,
			&i.Provider,
			&i.Model,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.InputMessageCount,
			&i.InputFirstMsgID,
			&i.InputLastMsgID,
			&i.ResponseText,
			&i.RawPayload,
			&i.ThoughtSignature,
			&i.AssistantPayload,
			&i.AssistantPayloadFormat,
			&i.CacheExpireAt,
			&i.CandidateStateJson,
			&i.ResponseChatID,
			&i.ResponseMsgID,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAISessionMessages = `-- name: ListAISessionMessages :many
SELECT sm.session_id, sm.position, sm.chat_id, sm.msg_id, sm.role, sm.quote_part, sm.context_only, m.sent_at, m.user_id, m.username, m.atable_username, m.msg_type, m.text, m.reply_to_msg_id
FROM ai_session_messages sm
JOIN ai_messages m ON m.chat_id=sm.chat_id AND m.msg_id=sm.msg_id
WHERE sm.session_id=?
  AND sm.context_only=0
ORDER BY sm.position
`

type ListAISessionMessagesRow struct {
	SessionID      int64          `json:"session_id"`
	Position       int64          `json:"position"`
	ChatID         int64          `json:"chat_id"`
	MsgID          int64          `json:"msg_id"`
	Role           string         `json:"role"`
	QuotePart      sql.NullString `json:"quote_part"`
	ContextOnly    int64          `json:"context_only"`
	SentAt         int64          `json:"sent_at"`
	UserID         int64          `json:"user_id"`
	Username       string         `json:"username"`
	AtableUsername sql.NullString `json:"atable_username"`
	MsgType        string         `json:"msg_type"`
	Text           sql.NullString `json:"text"`
	ReplyToMsgID   sql.NullInt64  `json:"reply_to_msg_id"`
}

func (q *Queries) ListAISessionMessages(ctx context.Context, sessionID int64) ([]ListAISessionMessagesRow, error) {
	rows, err := q.query(ctx, q.listAISessionMessagesStmt, listAISessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAISessionMessagesRow
	for rows.Next() {
		var i ListAISessionMessagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Position,
			&i.ChatID,
			&i.MsgID,
			&i.Role,
			&i.QuotePart,
			&i.ContextOnly,
			&i.SentAt,
			&i.UserID,
			&i.Username,
			&i.AtableUsername,
			&i.MsgType,
			&i.Text,
			&i.ReplyToMsgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedMediaHashes = `-- name: ListReferencedMediaHashes :many
SELECT DISTINCT media_sha256 FROM ai_message_media ORDER BY media_sha256
`

func (q *Queries) ListReferencedMediaHashes(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listReferencedMediaHashesStmt, listReferencedMediaHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var media_sha256 string
		if err := rows.Scan(&media_sha256); err != nil {
			return nil, err
		}
		items = append(items, media_sha256)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIMessageAsUserInput = `-- name: MarkAIMessageAsUserInput :exec
UPDATE ai_session_messages
SET role = 'user'
WHERE chat_id = ?1 AND msg_id = ?2
  AND NOT EXISTS (
      SELECT 1 FROM ai_runs
      WHERE response_chat_id = ?1 AND response_msg_id = ?2
  )
`

func (q *Queries) MarkAIMessageAsUserInput(ctx context.Context, chatID int64, msgID int64) error {
	_, err := q.exec(ctx, q.markAIMessageAsUserInputStmt, markAIMessageAsUserInput, chatID, msgID)
	return err
}

const markAIRunDelivered = `-- name: MarkAIRunDelivered :execrows
UPDATE ai_runs
SET status='delivered', response_chat_id=?1,
    response_msg_id=?2, error_code=NULL, error_message=NULL
WHERE id=?3 AND status IN ('generated', 'delivery_failed')
`

func (q *Queries) MarkAIRunDelivered(ctx context.Context, responseChatID sql.NullInt64, responseMsgID sql.NullInt64, runID int64) (int64, error) {
	result, err := q.exec(ctx, q.markAIRunDeliveredStmt, markAIRunDelivered, responseChatID, responseMsgID, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAIRunFailed = `-- name: MarkAIRunFailed :execrows
UPDATE ai_runs
SET status=?1, completed_at=?2,
    error_code=?3, error_message=?4
WHERE id=?5 AND status IN ('pending', 'generated', 'delivery_failed')
`

type MarkAIRunFailedParams struct {
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	RunID        int64          `json:"run_id"`
}

func (q *Queries) MarkAIRunFailed(ctx context.Context, arg MarkAIRunFailedParams) (int64, error) {
	result, err := q.exec(ctx, q.markAIRunFailedStmt, markAIRunFailed,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAIRunGenerated = `-- name: MarkAIRunGenerated :execrows
UPDATE ai_runs
SET status='generated', completed_at=?1,
    input_tokens=?2, output_tokens=?3,
    cached_input_tokens=?4,
    input_message_count=?5,
    input_first_msg_id=?6, input_last_msg_id=?7,
    response_text=?8, raw_payload=?9,
    thought_signature=?10,
    assistant_payload=?11, assistant_payload_format=?12,
    cache_expire_at=?13, candidate_state_json=?14,
    error_code=NULL, error_message=NULL
WHERE id=?15 AND status='pending'
`

type MarkAIRunGeneratedParams struct {
	CompletedAt            sql.NullInt64  `json:"completed_at"`
	InputTokens            sql.NullInt64  `json:"input_tokens"`
	OutputTokens           sql.NullInt64  `json:"output_tokens"`
	CachedInputTokens      sql.NullInt64  `json:"cached_input_tokens"`
	InputMessageCount      sql.NullInt64  `json:"input_message_count"`
	InputFirstMsgID        sql.NullInt64  `json:"input_first_msg_id"`
	InputLastMsgID         sql.NullInt64  `json:"input_last_msg_id"`
	ResponseText           sql.NullString `json:"response_text"`
	RawPayload             []byte         `json:"raw_payload"`
	ThoughtSignature       sql.NullString `json:"thought_signature"`
	AssistantPayload       []byte         `json:"assistant_payload"`
	AssistantPayloadFormat sql.NullString `json:"assistant_payload_format"`
	CacheExpireAt          sql.NullInt64  `json:"cache_expire_at"`
	CandidateStateJson     sql.NullString `json:"candidate_state_json"`
	RunID                  int64          `json:"run_id"`
}

func (q *Queries) MarkAIRunGenerated(ctx context.Context, arg MarkAIRunGeneratedParams) (int64, error) {
	result, err := q.exec(ctx, q.markAIRunGeneratedStmt, markAIRunGenerated,
		arg.CompletedAt,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedInputTokens,
		arg.InputMessageCount,
		arg.InputFirstMsgID,
		arg.InputLastMsgID,
		arg.ResponseText,
		arg.RawPayload,
		arg.ThoughtSignature,
		arg.AssistantPayload,
		arg.AssistantPayloadFormat,
		arg.CacheExpireAt,
		arg.CandidateStateJson,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAIChatModelSetting = `-- name: SetAIChatModelSetting :one
INSERT INTO ai_chat_settings(chat_id, default_provider, default_model, show_usage, updated_at)
VALUES (?1, ?2, ?3, 0, ?4)
ON CONFLICT(chat_id) DO UPDATE SET
    default_provider=excluded.default_provider,
    default_model=excluded.default_model,
    updated_at=excluded.updated_at
RETURNING chat_id, default_provider, default_model, show_usage, updated_at
`

func (q *Queries) SetAIChatModelSetting(ctx context.Context, chatID int64, defaultProvider string, defaultModel string, updatedAt int64) (AiChatSetting, error) {
	row := q.queryRow(ctx, q.setAIChatModelSettingStmt, setAIChatModelSetting,
		chatID,
		defaultProvider,
		defaultModel,
		updatedAt,
	)
	var i AiChatSetting
	err := row.Scan(
		&i.ChatID,
		&i.DefaultProvider,
		&i.DefaultModel,
		&i.ShowUsage,
		&i.UpdatedAt,
	)
	return i, err
}

const setAISessionModel = `-- name: SetAISessionModel :exec
UPDATE ai_sessions
SET provider=?1, model=?2, history_rebuild_lossy=1,
    updated_at=?3
WHERE id=?4
`

func (q *Queries) SetAISessionModel(ctx context.Context, provider string, model string, updatedAt int64, sessionID int64) error {
	_, err := q.exec(ctx, q.setAISessionModelStmt, setAISessionModel,
		provider,
		model,
		updatedAt,
		sessionID,
	)
	return err
}

const setAISessionStatus = `-- name: SetAISessionStatus :exec
UPDATE ai_sessions
SET status=?1, updated_at=?2
WHERE id=?3
`

func (q *Queries) SetAISessionStatus(ctx context.Context, status string, updatedAt int64, sessionID int64) error {
	_, err := q.exec(ctx, q.setAISessionStatusStmt, setAISessionStatus, status, updatedAt, sessionID)
	return err
}

const toggleAIChatSettingsUsage = `-- name: ToggleAIChatSettingsUsage :one
INSERT INTO ai_chat_settings(chat_id, default_provider, default_model, show_usage, updated_at)
VALUES (?1, ?2, ?3, 1, ?4)
ON CONFLICT(chat_id) DO UPDATE SET
    show_usage=NOT ai_chat_settings.show_usage,
    updated_at=excluded.updated_at
RETURNING chat_id, default_provider, default_model, show_usage, updated_at
`

func (q *Queries) ToggleAIChatSettingsUsage(ctx context.Context, chatID int64, defaultProvider string, defaultModel string, updatedAt int64) (AiChatSetting, error) {
	row := q.queryRow(ctx, q.toggleAIChatSettingsUsageStmt, toggleAIChatSettingsUsage,
		chatID,
		defaultProvider,
		defaultModel,
		updatedAt,
	)
	var i AiChatSetting
	err := row.Scan(
		&i.ChatID,
		&i.DefaultProvider,
		&i.DefaultModel,
		&i.ShowUsage,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAISession = `-- name: TouchAISession :exec
UPDATE ai_sessions SET updated_at=?1 WHERE id=?2
`

func (q *Queries) TouchAISession(ctx context.Context, updatedAt int64, sessionID int64) error {
	_, err := q.exec(ctx, q.touchAISessionStmt, touchAISession, updatedAt, sessionID)
	return err
}

const upsertAIChatSettings = `-- name: UpsertAIChatSettings :one
INSERT INTO ai_chat_settings(chat_id, default_provider, default_model, show_usage, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(chat_id) DO UPDATE SET
    default_provider=excluded.default_provider,
    default_model=excluded.default_model,
    show_usage=excluded.show_usage,
    updated_at=excluded.updated_at
RETURNING chat_id, default_provider, default_model, show_usage, updated_at
`

type UpsertAIChatSettingsParams struct {
	ChatID          int64  `json:"chat_id"`
	DefaultProvider string `json:"default_provider"`
	DefaultModel    string `json:"default_model"`
	ShowUsage       int64  `json:"show_usage"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpsertAIChatSettings(ctx context.Context, arg UpsertAIChatSettingsParams) (AiChatSetting, error) {
	row := q.queryRow(ctx, q.upsertAIChatSettingsStmt, upsertAIChatSettings,
		arg.ChatID,
		arg.DefaultProvider,
		arg.DefaultModel,
		arg.ShowUsage,
		arg.UpdatedAt,
	)
	var i AiChatSetting
	err := row.Scan(
		&i.ChatID,
		&i.DefaultProvider,
		&i.DefaultModel,
		&i.ShowUsage,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAISessionProviderState = `-- name: UpsertAISessionProviderState :exec
INSERT INTO ai_session_provider_state(session_id, provider, state_version, state_json, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    provider=excluded.provider, state_version=excluded.state_version,
    state_json=excluded.state_json, updated_at=excluded.updated_at
`

type UpsertAISessionProviderStateParams struct {
	SessionID    int64  `json:"session_id"`
	Provider     string `json:"provider"`
	StateVersion int64  `json:"state_version"`
	StateJson    string `json:"state_json"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertAISessionProviderState(ctx context.Context, arg UpsertAISessionProviderStateParams) error {
	_, err := q.exec(ctx, q.upsertAISessionProviderStateStmt, upsertAISessionProviderState,
		arg.SessionID,
		arg.Provider,
		arg.StateVersion,
		arg.StateJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertAISystemPrompt = `-- name: UpsertAISystemPrompt :exec
INSERT INTO ai_system_prompts(chat_id, topic_id, prompt, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(chat_id, topic_id) DO UPDATE SET prompt=excluded.prompt, updated_at=excluded.updated_at
`

func (q *Queries) UpsertAISystemPrompt(ctx context.Context, chatID int64, topicID int64, prompt string, updatedAt int64) error {
	_, err := q.exec(ctx, q.upsertAISystemPromptStmt, upsertAISystemPrompt,
		chatID,
		topicID,
		prompt,
		updatedAt,
	)
	return err
}
