// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package legacyq

import (
	"database/sql"
)

type AiChatModel struct {
	ChatID    int64  `json:"chat_id"`
	Model     string `json:"model"`
	ShowUsage int64  `json:"show_usage"`
}

type AiMessageMetum struct {
	SessionID              int64          `json:"session_id"`
	MsgID                  int64          `json:"msg_id"`
	ChatID                 int64          `json:"chat_id"`
	Provider               string         `json:"provider"`
	Model                  string         `json:"model"`
	InputTokens            int64          `json:"input_tokens"`
	OutputTokens           int64          `json:"output_tokens"`
	CachedInputTokens      int64          `json:"cached_input_tokens"`
	InputMessageCount      int64          `json:"input_message_count"`
	InputFirstMsgID        int64          `json:"input_first_msg_id"`
	InputLastMsgID         int64          `json:"input_last_msg_id"`
	AssistantPayload       []byte         `json:"assistant_payload"`
	AssistantPayloadFormat sql.NullString `json:"assistant_payload_format"`
}

type AiSessionMetum struct {
	SessionID              int64          `json:"session_id"`
	Provider               string         `json:"provider"`
	Model                  string         `json:"model"`
	CachedInputTokens      int64          `json:"cached_input_tokens"`
	GeminiInteractionID    sql.NullString `json:"gemini_interaction_id"`
	WindowStartMsgID       sql.NullInt64  `json:"window_start_msg_id"`
	GeminiCacheName        sql.NullString `json:"gemini_cache_name"`
	GeminiCacheExpireTime  sql.NullInt64  `json:"gemini_cache_expire_time"`
	GeminiCacheStartMsgID  sql.NullInt64  `json:"gemini_cache_start_msg_id"`
	GeminiCacheEndMsgID    sql.NullInt64  `json:"gemini_cache_end_msg_id"`
	GeminiCacheTokenCount  int64          `json:"gemini_cache_token_count"`
	GeminiCacheFingerprint sql.NullString `json:"gemini_cache_fingerprint"`
	HistoryRebuildLossy    int64          `json:"history_rebuild_lossy"`
}

type GeminiContent struct {
	SessionID        int64          `json:"session_id"`
	ChatID           int64          `json:"chat_id"`
	MsgID            int64          `json:"msg_id"`
	Role             string         `json:"role"`
	SentTime         int64          `json:"sent_time"`
	Username         string         `json:"username"`
	MsgType          string         `json:"msg_type"`
	ReplyToMsgID     sql.NullInt64  `json:"reply_to_msg_id"`
	Text             sql.NullString `json:"text"`
	Blob             []byte         `json:"blob"`
	MimeType         sql.NullString `json:"mime_type"`
	QuotePart        sql.NullString `json:"quote_part"`
	ThoughtSignature sql.NullString `json:"thought_signature"`
	AtableUsername   sql.NullString `json:"atable_username"`
	UserID           int64          `json:"user_id"`
}

type GeminiMessage struct {
	ID          int64         `json:"id"`
	SessionID   int64         `json:"session_id"`
	ChatID      int64         `json:"chat_id"`
	TgMessageID int64         `json:"tg_message_id"`
	FromID      int64         `json:"from_id"`
	Role        string        `json:"role"`
	Content     string        `json:"content"`
	Seq         int64         `json:"seq"`
	ReplyToSeq  sql.NullInt64 `json:"reply_to_seq"`
	CreatedAt   int64         `json:"created_at"`
}

type GeminiSession struct {
	ID                int64  `json:"id"`
	ChatID            int64  `json:"chat_id"`
	ChatName          string `json:"chat_name"`
	ChatType          string `json:"chat_type"`
	Frozen            int64  `json:"frozen"`
	TotalInputTokens  int64  `json:"total_input_tokens"`
	TotalOutputTokens int64  `json:"total_output_tokens"`
}

type GeminiSessionMigration struct {
	ID             int64          `json:"id"`
	OldSessionID   int64          `json:"old_session_id"`
	NewSessionID   int64          `json:"new_session_id"`
	MigratedMsgIds string         `json:"migrated_msg_ids"`
	Reason         sql.NullString `json:"reason"`
	RequestedBy    sql.NullString `json:"requested_by"`
	CreatedAt      int64          `json:"created_at"`
}

type GeminiSystemPrompt struct {
	ChatID   int64  `json:"chat_id"`
	ThreadID int64  `json:"thread_id"`
	Prompt   string `json:"prompt"`
}
