// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_ai_v1.sql

package legacyq

import (
	"context"
	"database/sql"
)

const listLegacyChatSettings = `-- name: ListLegacyChatSettings :many
SELECT chat_id, model, show_usage
FROM ai_chat_models
ORDER BY chat_id
`

func (q *Queries) ListLegacyChatSettings(ctx context.Context) ([]AiChatModel, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyChatSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatModel
	for rows.Next() {
		var i AiChatModel
		if err := rows.Scan(&i.ChatID, &i.Model, &i.ShowUsage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyMessages = `-- name: ListLegacyMessages :many
SELECT c.session_id, c.chat_id, c.msg_id, c.role, c.sent_time,
       c.username, c.msg_type, c.reply_to_msg_id, c.text, c.blob,
       c.mime_type, c.quote_part, c.thought_signature,
       c.atable_username, c.user_id,
       m.provider AS response_provider, m.model AS response_model,
       m.input_tokens, m.output_tokens, m.cached_input_tokens,
       m.input_message_count, m.input_first_msg_id, m.input_last_msg_id,
       m.assistant_payload, m.assistant_payload_format
FROM gemini_contents AS c
LEFT JOIN ai_message_meta AS m
  ON m.session_id=c.session_id AND m.msg_id=c.msg_id
ORDER BY c.session_id, c.sent_time, c.msg_id
`

type ListLegacyMessagesRow struct {
	SessionID              int64          `json:"session_id"`
	ChatID                 int64          `json:"chat_id"`
	MsgID                  int64          `json:"msg_id"`
	Role                   string         `json:"role"`
	SentTime               int64          `json:"sent_time"`
	Username               string         `json:"username"`
	MsgType                string         `json:"msg_type"`
	ReplyToMsgID           sql.NullInt64  `json:"reply_to_msg_id"`
	Text                   sql.NullString `json:"text"`
	Blob                   []byte         `json:"blob"`
	MimeType               sql.NullString `json:"mime_type"`
	QuotePart              sql.NullString `json:"quote_part"`
	ThoughtSignature       sql.NullString `json:"thought_signature"`
	AtableUsername         sql.NullString `json:"atable_username"`
	UserID                 int64          `json:"user_id"`
	ResponseProvider       sql.NullString `json:"response_provider"`
	ResponseModel          sql.NullString `json:"response_model"`
	InputTokens            sql.NullInt64  `json:"input_tokens"`
	OutputTokens           sql.NullInt64  `json:"output_tokens"`
	CachedInputTokens      sql.NullInt64  `json:"cached_input_tokens"`
	InputMessageCount      sql.NullInt64  `json:"input_message_count"`
	InputFirstMsgID        sql.NullInt64  `json:"input_first_msg_id"`
	InputLastMsgID         sql.NullInt64  `json:"input_last_msg_id"`
	AssistantPayload       []byte         `json:"assistant_payload"`
	AssistantPayloadFormat sql.NullString `json:"assistant_payload_format"`
}

func (q *Queries) ListLegacyMessages(ctx context.Context) ([]ListLegacyMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacyMessagesRow
	for rows.Next() {
		var i ListLegacyMessagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ChatID,
			&i.MsgID,
			&i.Role,
			&i.SentTime,
			&i.Username,
			&i.MsgType,
			&i.ReplyToMsgID,
			&i.Text,
			&i.Blob,
			&i.MimeType,
			&i.QuotePart,
			&i.ThoughtSignature,
			&i.AtableUsername,
			&i.UserID,
			&i.ResponseProvider,
			&i.ResponseModel,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedInputTokens,
			&i.InputMessageCount,
			&i.InputFirstMsgID,
			&i.InputLastMsgID,
			&i.AssistantPayload,
			&i.AssistantPayloadFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacySessions = `-- name: ListLegacySessions :many
SELECT s.id, s.chat_id, s.chat_name, s.chat_type, s.frozen,
       s.total_input_tokens, s.total_output_tokens,
       CAST(COALESCE(MIN(c.sent_time), 0) AS INTEGER) AS first_message_at,
       CAST(COALESCE(MAX(c.sent_time), 0) AS INTEGER) AS last_message_at,
       m.provider, m.model, m.cached_input_tokens,
       m.gemini_interaction_id, m.window_start_msg_id,
       m.gemini_cache_name, m.gemini_cache_expire_time,
       m.gemini_cache_start_msg_id, m.gemini_cache_end_msg_id,
       m.gemini_cache_token_count, m.gemini_cache_fingerprint,
       m.history_rebuild_lossy
FROM gemini_sessions AS s
LEFT JOIN (
    SELECT session_id, sent_time FROM gemini_contents
    UNION ALL
    SELECT m.session_id, m.created_at
    FROM gemini_messages AS m
    WHERE NOT EXISTS (
        SELECT 1 FROM gemini_contents AS c
        WHERE c.chat_id=m.chat_id AND c.msg_id=m.tg_message_id
    )
) AS c ON c.session_id=s.id
LEFT JOIN ai_session_meta AS m ON m.session_id=s.id
GROUP BY s.id
ORDER BY s.id
`

type ListLegacySessionsRow struct {
	ID                     int64          `json:"id"`
	ChatID                 int64          `json:"chat_id"`
	ChatName               string         `json:"chat_name"`
	ChatType               string         `json:"chat_type"`
	Frozen                 int64          `json:"frozen"`
	TotalInputTokens       int64          `json:"total_input_tokens"`
	TotalOutputTokens      int64          `json:"total_output_tokens"`
	FirstMessageAt         int64          `json:"first_message_at"`
	LastMessageAt          int64          `json:"last_message_at"`
	Provider               sql.NullString `json:"provider"`
	Model                  sql.NullString `json:"model"`
	CachedInputTokens      sql.NullInt64  `json:"cached_input_tokens"`
	GeminiInteractionID    sql.NullString `json:"gemini_interaction_id"`
	WindowStartMsgID       sql.NullInt64  `json:"window_start_msg_id"`
	GeminiCacheName        sql.NullString `json:"gemini_cache_name"`
	GeminiCacheExpireTime  sql.NullInt64  `json:"gemini_cache_expire_time"`
	GeminiCacheStartMsgID  sql.NullInt64  `json:"gemini_cache_start_msg_id"`
	GeminiCacheEndMsgID    sql.NullInt64  `json:"gemini_cache_end_msg_id"`
	GeminiCacheTokenCount  sql.NullInt64  `json:"gemini_cache_token_count"`
	GeminiCacheFingerprint sql.NullString `json:"gemini_cache_fingerprint"`
	HistoryRebuildLossy    sql.NullInt64  `json:"history_rebuild_lossy"`
}

func (q *Queries) ListLegacySessions(ctx context.Context) ([]ListLegacySessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacySessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacySessionsRow
	for rows.Next() {
		var i ListLegacySessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ChatName,
			&i.ChatType,
			&i.Frozen,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.FirstMessageAt,
			&i.LastMessageAt,
			&i.Provider,
			&i.Model,
			&i.CachedInputTokens,
			&i.GeminiInteractionID,
			&i.WindowStartMsgID,
			&i.GeminiCacheName,
			&i.GeminiCacheExpireTime,
			&i.GeminiCacheStartMsgID,
			&i.GeminiCacheEndMsgID,
			&i.GeminiCacheTokenCount,
			&i.GeminiCacheFingerprint,
			&i.HistoryRebuildLossy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacySystemPrompts = `-- name: ListLegacySystemPrompts :many
SELECT chat_id, thread_id, prompt
FROM gemini_system_prompt
ORDER BY chat_id, thread_id
`

func (q *Queries) ListLegacySystemPrompts(ctx context.Context) ([]GeminiSystemPrompt, error) {
	rows, err := q.db.QueryContext(ctx, listLegacySystemPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeminiSystemPrompt
	for rows.Next() {
		var i GeminiSystemPrompt
		if err := rows.Scan(&i.ChatID, &i.ThreadID, &i.Prompt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyV0Messages = `-- name: ListLegacyV0Messages :many
SELECT m.session_id, m.chat_id, m.tg_message_id AS msg_id, m.role,
       m.created_at AS sent_time, r.tg_message_id AS reply_to_msg_id,
       m.content AS text, m.from_id AS user_id
FROM gemini_messages AS m
LEFT JOIN gemini_messages AS r
  ON r.session_id=m.session_id AND r.seq=m.reply_to_seq
WHERE NOT EXISTS (
    SELECT 1 FROM gemini_contents AS c
    WHERE c.chat_id=m.chat_id AND c.msg_id=m.tg_message_id
)
ORDER BY m.session_id, m.created_at, m.tg_message_id
`

type ListLegacyV0MessagesRow struct {
	SessionID    int64         `json:"session_id"`
	ChatID       int64         `json:"chat_id"`
	MsgID        int64         `json:"msg_id"`
	Role         string        `json:"role"`
	SentTime     int64         `json:"sent_time"`
	ReplyToMsgID sql.NullInt64 `json:"reply_to_msg_id"`
	Text         string        `json:"text"`
	UserID       int64         `json:"user_id"`
}

func (q *Queries) ListLegacyV0Messages(ctx context.Context) ([]ListLegacyV0MessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyV0Messages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacyV0MessagesRow
	for rows.Next() {
		var i ListLegacyV0MessagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ChatID,
			&i.MsgID,
			&i.Role,
			&i.SentTime,
			&i.ReplyToMsgID,
			&i.Text,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
